parameters:
  - name: actionGroups
    type: object
    default: []
  - name: enableProduction
    type: boolean
    default: false
  - name: runReviewStage
    type: boolean
    default: true
  - name: drInvocation
    type: boolean
    default: false
  - name: skip_environments
    type: object
    default:
      dev: false
      qa: false
      ppr: false

resources:
  repositories:
    - repository: PipelineDispatcher
      type: github
      endpoint: wesley-trust
      name: wesley-trust/pipeline-dispatcher
      ref: "refs/heads/feature/default-settings"
      #ref: "refs/heads/main"

extends:
  template: /templates/pipeline-defaults.yml@PipelineDispatcher
  parameters:
    ${{ each parameter in parameters }}:
      ${{ parameter.key }}: ${{ parameter.value }}
    # Default Overrides
    variables:
      includeCommon: true
      includeEnv: true
      includeEnvRegion: true
      includeRegion: true
